### ISSUE TITLE
How to test on single image?

### ISSUE THREAD

**Issue by viliusmat** [face-alignment-group-of-ahucs/SHN-based-2D-face-alignment#6]
Hello, Than you for sharing your work. I have trained a model, now I whant to test it on single image. How can I do that?

**Comment by 738654805** [comment]
Just load the trained model and read the image data. Please leave your email address below so that I can send you the code. @viliusmat

**Comment by viliusmat** [comment]
Thank you. 
vilius.matiukas@gmail.com

**Comment by Happythinker** [comment]
> Thank you.
> [vilius.matiukas@gmail.com](mailto:vilius.matiukas@gmail.com)

Could you tell me how to test on single image?

**Comment by Happythinker** [comment]
> Just load the trained model and read the image data. Please leave your email address below so that I can send you the code. @viliusmat
Could you tell me how to test on single image?
@viliusmat @738654805

**Comment by Happythinker** [comment]
> Just load the trained model and read the image data. Please leave your email address below so that I can send you the code. @viliusmat
Could you tell me how to test on single image?
@viliusmat @738654805
my email address is 991159327@qq.com
thank you very much

**Comment by silvercherry** [comment]
> Just load the trained model and read the image data. Please leave your email address below so that I can send you the code. @viliusmat

请问您已经复现出来这个了吗 我测试的时候效果很差

**Comment by Happythinker** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"silvercherry"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月19日(星期四) 中午1:42
收件人:&nbsp;"face-alignment-group-of-ahucs/SHN-based-2D-face-alignment"<SHN-based-2D-face-alignment@noreply.github.com&gt;;
抄送:&nbsp;"(•ิ_•ิ)?"<626713121@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [face-alignment-group-of-ahucs/SHN-based-2D-face-alignment] How to test on single image? (#6)



 
Just load the trained model and read the image data. Please leave your email address below so that I can send you the code. @viliusmat
  
请问您已经复现出来这个了吗 我测试的时候效果很差

请问您的单幅图像测试是怎么实现的呢
